console.log('Hello Winc Academy');
let name = 'Nienke';
console.log(name);
let sum = 3 + 4;
console.log("Sum:", sum);
let sumWithStrings = "3" + "4";
console.log("sumWithStrings:", sumWithStrings);
let subtraction = 10 - 3;
console.log("subtraction:", subtraction);
let multiplication = 4 * 10;
console.log("multiplication:", multiplication);
let division = 12 / 3;
console.log("division:", division);
let modulus = 12 % 9;
console.log("modulus:", modulus);
var age = 27;
console.log(typeof age);
var age = "27";
console.log(typeof age);